export { default as SvSignin } from './signin/signin.vue'
export { default as SvCrudView } from './dashboard/crud-view/crud-view.vue'
export { default as SvAccessProfile } from './dashboard/access-profile/access-profile-edit.vue'
export { default as SvPasswordChange } from './dashboard/user/password-change/password-change.vue'
export { default as SvProfile } from './dashboard/user/profile/profile.vue'
